<div class="container">
	<h1>Design your own apparel</h1>
	<p>Our design studio allows you to design your next apparel yourself.  Just pick the garment you want and start designing.  Don't have your own artwork? No problem.  We have plenty of high-quality customisable artwork to get you started.  If you're looking for something really different, just send us a note and one of our artists will help you out!</p>
</div>
<div class="design-studio">
    <script type="text/javascript" language="javascript" src="http://stores.inksoft.com/designer/html5/common/js/launcher.js"></script>
    <div align="center" id="embeddedDesigner"></div>
    <script type="text/javascript" language="javascript">
        var flashvars = {
EnforceBoundaries: "0",
Background: "white",
VectorOnly: false,
DigitalPrint: true,
ScreenPrint: true,
Embroidery: false,
MaxScreenPrintColors: "6",
StoreID: "14063",
PublisherID: "3156",
SessionID: "",
SessionToken: "",
UserID: "",
UserName: "",
UserEmail: "",
ProductID: "1000000",
ProductStyleID: "1000043",
ProductCategoryID: "1000001",
DesignID: "",
ArtID: "",
EnableBranding: false,
DisableUploadImage: false,
DisableAddToCart: false,
DisableClipArt: false,
DisableUserArt: false,
DisableProducts: false,
DisableDesigns: false,
DisableDistress: false,
StartPage: "Products",
StartPageCategoryID: "",
StartPageHTML: "",
ClipArtGalleryID: "",
Domain: "stores.inksoft.com",
SSLEnabled: false,
SSLDomain: "",
StoreURI: "Inkmule",
DefaultProductID: "1000000",
DefaultProductStyleID: "1000043",
DisableResolutionMeter: true,
DisableUploadVectorArt: true,
DisableUploadRasterArt: false,
Admin: "None",
NextURL: "",
CartURL: "/Inkmule/Cart",
OrderSummary: true,
Phone: "919-810-6049",
VideoLink: "http://www.youtube.com/watch?v=EfXICdRwt4E",
WelcomeScreen: "",
ContactUsLink: "http://stores.inksoft.com/Inkmule/Stores/Contact",
WelcomeVideo: "",
HelpVideoOverview: "",
AutoZoom: false,
EnableNameNumbers: true,
AddThisPublisherId: "xa-4fccb0966fef0ba7",
EnableCartPricing: true,
EnableCartCheckout: true,
EnableCartBilling: false,
PaymentDisabled: false,
PaymentRequired: true,
BillingAddressRequired: true,
EnableCartShipping: true,
PasswordLength: "",
CurrencyCode: "USD",
CurrencySymbol: "$",
HideProductPricing: "False",
HideClipArtNames: true,
HideDesignNames: true,
DesignerLocation: "http://stores.inksoft.com/designer/html5",
ThemeName: "flat",
EmbedType: "iframe",
BackgroundColor: ""};
        launchDesigner('HTML5DS', flashvars, document.getElementById("embeddedDesigner"));
    </script>
</div>